### ISSUE TITLE
Could you please add the code you submitted to the IEEE CEC2011 Competition?

### ISSUE THREAD

**Issue by eugenrein** [emiliomartin84/AntBot#1]
I'm currently working on my master thesis which is about implementing a population based algorithm (SPPBO - kind of ACO) to optimize paths in the Ms Pac-Man game. I've read your paper "AntBot: Ant Colonies for Video Games", but I'm struggling getting the same results as you did. Is there any chance that you could push the code you submitted to the IEEE CEC2011?

**Comment by emiliomartin84** [comment]
Hi @eugenrein, I've just updated both controllers for CEC 2011.  Sorry for the 1 year delay ;)
